all: $(patsubst %.fasta, lnL_%.csv, $(wildcard *.fasta)) results.csv

clean:
	rm -drf results

%.phy: %.fasta
	python ./scripts/01_converter.py $< $@
	mkdir -p results/$*
	mv $@ results/$*

lnL_%.csv: %.phy
ifeq ($(method),branchsites2)
mkdir results/$*/alternative
python ./scripts/02_codeml.py $< *.tre alternative
mkdir results/$*/null
python ./scripts/02_codeml.py $< *.tre null
else
ifeq ($(method),branchsites1)
mkdir results/$*/alternative
python ./scripts/02_codeml.py $< *.tre alternative
mkdir results/$*/m1
python ./scripts/02_codeml.py $< *.tre m1
else
ifeq ($(method),branch)
mkdir results/$*/m0
python ./scripts/02_codeml.py $< *.tre m0
mkdir results/$*/nratios
python ./scripts/02_codeml.py $< *.tre nratios
else
mkdir results/$*/$(method)
python ./scripts/02_codeml.py $< *.tre $(method)
endif

lnL_results = $(wildcard lnL_*.csv)

results.csv: $(lnL_results)
	find ./results -type f -mindepth 2 -wholename *.csv -exec cat {} \; > ./results/$@

.PHONY: all branchsites2 branchsites1 alternative null m1 clean
.DELETE_ON_ERROR:
.SECONDARY:
